version: "3.9"

services:

  rabbitmq:
    image: masstransit/rabbitmq
    container_name: grackermq
    restart: unless-stopped
    ports:
      - "17751:5672"
      - "17752:15672"
    environment:
      - "RABBITMQ_DEFAULT_USER=guest"
      - "RABBITMQ_DEFAULT_PASS=guest"

  db:
    image: postgres
    container_name: grackerdb
    restart: unless-stopped
    shm_size: 256MB
    ports:
      - "17753:5432"
    environment:
      - POSTGRES_DB=gracker
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123

  adminer:
    image: adminer
    restart: unless-stopped
    environment:
      - "ADMINER_DEFAULT_SERVER=db"
    ports:
      - 17754:8080
